### ISSUE TITLE
Fails to compile with Gnome Shell 3.34

### ISSUE THREAD

**Issue by inducer** [timbertson/slinger#18]
On Debian's `node-typescript` 3.6-1, I get the following:

```
$ ./tools/gup compile
gup  compile
gup    schemas/all
gup      schemas/gschemas.compiled
+ mkdir -p compiled
+ gup -u inputs
gup        schemas/inputs
+ glib-compile-schemas . --targetdir=compiled
+ mv compiled/gschemas.compiled /home/andreas/pack/slinger/schemas/.gup/out.gschemas.compiled
+ rm -rf compiled
gup    extension/all
gup      extension/extension_impl.js
../node_modules/@types/node/globals.d.ts:163:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'global' must be of type 'Global', but here has type 'Global'.

163 declare var global: NodeJS.Global;
                ~~~~~~

  src/gnome_shell.ts:36:13
    36 declare var global: Global;
                   ~~~~~~
    'global' was also declared here.


Found 1 error.

gup      Target `extension/extension_impl.js` failed with exit status 2
gup    Target `extension/all` failed with exit status 2
gup  Target `compile` failed with exit status 2
```

**Comment by inducer** [comment]
Ostensibly, my issue was that I tried to build in a folder for which a parent directory had a `node_modules` containing type annotations for Node containing the offending declaration. Moving that out of the way got rid of the error.

Sorry for the noise, and thanks for Slinger!
